# A CI configuration to auto-publish pub packages.

name: Publish

on:
  # Run on PRs for general validation (changelog, pubspec version, ...).
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled, unlabeled]
  # Run on git tags to perform the publish.
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  auto-publish:
    # Update this to the host GitHub org.
    if: github.repository_owner == 'devoncarew'

    # This is required for authentication using OIDC.
    permissions:
      id-token: write 

    runs-on: ubuntu-latest
    steps:
      # Fetches all commits in order to determine the changed files.
      - name: Check out repo
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          fetch-depth: 0

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1.4

      - name: Install Firehose
        run: dart pub global activate firehose

      - name: Validate package changes
        if: ${{ github.event_name == 'pull_request' }}
        run: dart pub global run firehose --verify
        env:
          PR_LABELS: "${{ join(github.event.pull_request.labels.*.name) }}"

      - name: Publish package
        if: ${{ github.event_name == 'push' }}
        run: dart pub global run firehose --publish
